// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://eniovljvaaycjepoykam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuaW92bGp2YWF5Y2plcG95a2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyOTcxNDgsImV4cCI6MjA4NTg3MzE0OH0.v3xFWxaL79GEinrOL1Ou-NMfNEH5RV_-6PbPdjTWQ8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);